

GET http://localhost:3306/user/9
Content-Type: application/json

# PUT http://localhost:3306/user
# Content-Type: application/json

# {
#     "name": "Carla",
#     "nickname": "Carlinha",
#     "email": "carlinha@gmail.com"
# }




# http://localhost:3306/getuser
# Content-Type: application/json
